Pizzario.Web/Models/Coupons.cs
using System.ComponentModel.DataAnnotations;

namespace Pizzario.Web.Models
{
    public class Coupons
    {
        public int CouponId { get; set; }
        public string CouponCode { get; set; }
        public double DiscountAmount { get; set; }
        public int MinAmount { get; set; }
    }
}

Pizzario.Web/Models/ErrorViewModel.cs
namespace Pizzario.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Pizzario.Web/Models/Products.cs
namespace Pizzario.Web.Models
{
    public class Products
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public double Price { get; set; }
        public string Description { get; set; }
        public string CategoryName { get; set; }
        public string? ImageUrl { get; set; }
    }
}

Pizzario.Web/Models/RequestDto.cs
using Pizzario.Web.Utility;
using System.Net.Mime;
using static Pizzario.Web.Utility.StaticDetails;

namespace Pizzario.Web.Models
{
    public class RequestDto
    {
        public ApiType ApiType { get; set; } = ApiType.GET;
        public string Url { get; set; }
        public object Data { get; set; }
        public string AccessToken { get; set; }
    }
}

Pizzario.Web/Models/ResponseDto.cs
namespace Pizzario.Web.Models
{
    public class ResponseDto
    {
        public object? Result { get; set; }
        public bool IsSuccess { get; set; } = true;
        public string Message { get; set; } = "";
    }
}

Pizzario.Web/Controllers/CouponController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Pizzario.Web.Models;
using Pizzario.Web.Service.IService;

namespace Pizzario.Web.Controllers
{
    public class CouponController : Controller
    {
        private readonly ICouponService _couponService;
        public CouponController(ICouponService couponService)
        {
            _couponService = couponService;
        }

        public async Task<IActionResult> CouponIndex()
        {
            //List<Coupons>? couponsList = new();
            //ResponseDto? response = await _couponService.GetAllCouponsAsync();
            //if (response != null && response.IsSuccess)
            //{
            //    couponsList = JsonConvert.DeserializeObject<List<Coupons>>(Convert.ToString(response.Result));
            //}
            //return View(couponsList);

            List<Coupons>? couponsList = new();
            var baseUrl = "http://localhost:5092"; // Ocelot gateway URL
            ResponseDto? response = await _couponService.GetAllCouponsAsync(baseUrl);
            if (response != null && response.IsSuccess)
            {
                couponsList = JsonConvert.DeserializeObject<List<Coupons>>(Convert.ToString(response.Result));
            }
            return View(couponsList);
        }

        [HttpPost]
        public async Task<IActionResult> CreateCoupon(Coupons coupons)
        {
            var baseUrl = "http://localhost:5092";
            if (ModelState.IsValid)
            {
                try
                {
                    ResponseDto response = await _couponService.CreateCouponAsync(coupons);
                    if (response.IsSuccess)
                    {
                        TempData["success"] = "Copon created successfully!";
                        return RedirectToAction("CouponIndex");
                    }
                    else
                    {
                        TempData["error"] = response?.Message;
                        ModelState.AddModelError("", "Failed to create coupon. Please try again.");
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", $"An error occurred: {ex.Message}");
                }
            }
            return View("CouponIndex", await _couponService.GetAllCouponsAsync(baseUrl));
        }

        //[HttpDelete]
        public async Task<IActionResult> DeleteCoupon(int couponId)
        {
            ResponseDto? response = await _couponService.DeleteCouponAsync(couponId);
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Copon deleted successfully!";
                return RedirectToAction("CouponIndex");

            }
            else
            {
                TempData["error"] = response?.Message;
            }
            return NotFound();
        }
    }
}

Pizzario.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Pizzario.Web.Models;
using Pizzario.Web.Service.IService;
using System.Diagnostics;

namespace Pizzario.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IProductService _productService;
        
        public HomeController(IProductService productService) { 
            _productService = productService;
        }

        public async Task<IActionResult> Index()
        {
            List<Products>? list = new();

            ResponseDto? response = await _productService.GetAllProductsAsync();

            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<Products>>(Convert.ToString(response.Result));
            }
            else
            {
                TempData["error"] = response?.Message;
            }

            return View(list);
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Pizzario.Web/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Pizzario.Web.Models;
using Pizzario.Web.Service.IService;

namespace Pizzario.Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        public async Task<IActionResult> ProductList()
        {
            List<Products>? productList = new List<Products>();
            ResponseDto? response = await _productService.GetAllProductsAsync();
            if (response != null && response.IsSuccess)
            {
                productList = JsonConvert.DeserializeObject<List<Products>>(Convert.ToString(response.Result));
            }
            return View(productList);
        }

        [HttpPost]
        public async Task<IActionResult> CreateProduct(Products product)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    ResponseDto response = await _productService.CreateProductAsync(product);
                    if (response.IsSuccess)
                    {
                        TempData["success"] = "Product created successfully!";
                        return RedirectToAction("ProductList");
                    }
                    else
                    {
                        TempData["error"] = response?.Message;
                        ModelState.AddModelError("", "Failed to create coupon. Please try again.");
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", $"An error occurred: {ex.Message}");
                }
            }
            return View("ProductList", await _productService.GetAllProductsAsync());
        }

        //[HttpDelete]
        public async Task<IActionResult> DeleteProduct(int productId)
        {
            ResponseDto? response = await _productService.DeleteProductAsync(productId);
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Product deleted successfully!";
                return RedirectToAction("ProductList");

            }
            else
            {
                TempData["error"] = response?.Message;
            }
            return NotFound();
        }
    }
}

Pizzario.Web/Views/Coupon/CouponIndex.cshtml
@model IEnumerable<Coupons>
@using System.Globalization

<div class="card border-primary mt-5">
    <div class="card-header d-flex">
        <h4 class="card-title">Coupon List</h4>
        <button type="button" class="btn btn-primary btn-sm ms-auto" data-bs-toggle="modal" data-bs-target="#createCouponModal">
            <i class="bi bi-patch-plus"></i> Create New Coupon
        </button>
    </div>
    <div class="card-body p-0">
        <table class="table table-hover mb-0">
            <thead>
                <tr>
                    <th scope="col">Coupon Code</th>
                    <th scope="col">Discount Amount</th>
                    <th scope="col">Minimum Amount</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="table-light">
                        <td scope="row">@item.CouponCode</td>
                        <td>@((item.DiscountAmount).ToString("C", new CultureInfo("en-IN")))</td>
                        <td>@((item.MinAmount).ToString("C", new CultureInfo("en-IN")))</td>
                        <td>
                            <a class="badge rounded-pill bg-danger" style="cursor: pointer" asp-route-couponId="@item.CouponId" data-bs-toggle="modal" data-bs-target="#deleteCouponModal" data-coupon-id="@item.CouponId">
                                <i class="bi bi-trash-fill"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>



<!-- Modal -->
<div class="modal fade" id="createCouponModal" tabindex="-1" aria-labelledby="createCouponModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header card-header">
                <h5 class="modal-title" id="createCouponModalLabel">Create New Coupon</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            @await Html.PartialAsync("_CreateCouponForm", new Coupons())
        </div>
    </div>
</div>

<div class="modal fade" id="deleteCouponModal" tabindex="-1" aria-labelledby="deleteCouponModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            @await Html.PartialAsync("_DeleteCoupon", new Coupons())
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var deleteCouponModal = document.getElementById('deleteCouponModal');
        deleteCouponModal.addEventListener('show.bs.modal', function (event) {
            var button = event.relatedTarget; // Button that triggered the modal
            var couponId = button.getAttribute('data-coupon-id'); // Extract info from data-* attributes

            var form = deleteCouponModal.querySelector('form');
            var input = form.querySelector('input[name="CouponId"]');
            input.value = couponId;
        });
    });
</script>

<!-- Bootstrap CSS -->
<link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet">

<!-- Bootstrap JS and dependencies (Popper.js) -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.10.2/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.min.js"></script>

Pizzario.Web/Views/Home/Index.cshtml
@model IEnumerable<Products>

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-sm-6 my-3 d-flex">
            <div class="card border-primary" style="max-width: 20rem;">
                <div class="card-header">@item.ProductName</div>
                <div class="card-body">
                    <img src="@Url.Content(item.ImageUrl)" alt="@item.ProductName" class="img-fluid" />
                </div>
                <div class="card-footer">
                    <div class="d-flex">
                        <h6 class="card-title">₹ @item.Price</h6>
                        <span class="badge rounded-pill bg-primary ms-auto">Pizza</span>
                    </div>
                    <div>
                        <div class="accordion" id="accordionExample">
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="headingOne">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                        Des.
                                    </button>
                                </h2>
                                <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <strong>@item.Description</strong>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <button class="btn btn-primary btn-sm mt-2" type="button" style="width: 100%;">
                        Details
                    </button>
                </div>
            </div>
        </div>
    }
</div>

Pizzario.Web/Views/Product/ProductList.cshtml
@model IEnumerable<Products>
@using System.Globalization

<div class="card border-primary mt-5">
    <div class="card-header d-flex">
        <h4 class="card-title">Product List</h4>
        <button type="button" class="btn btn-primary btn-sm ms-auto" data-bs-toggle="modal" data-bs-target="#createProductModal">
            <i class="bi bi-patch-plus"></i> Create New Product
        </button>
    </div>
    <div class="card-body p-0">
        <table class="table table-hover mb-0">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Category</th>
                    <th scope="col">Description</th>
                    <th scope="col">Price</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="table-light">
                        <td scope="row">@item.ProductName</td>
                        <td scope="row">@item.CategoryName</td>
                        <td scope="row">@item.Description</td>
                        <td style="min-width:85px">@((item.Price).ToString("C", new CultureInfo("en-IN")))</td>
                        <td>
                            <a class="badge rounded-pill bg-danger" style="cursor: pointer" asp-route-productId="@item.ProductId" data-bs-toggle="modal" data-bs-target="#deleteProductModal" data-product-id="@item.ProductId">
                                <i class="bi bi-trash-fill"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>



<!-- Modal -->
<div class="modal fade" id="createProductModal" tabindex="-1" aria-labelledby="createProductModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header card-header">
                <h5 class="modal-title" id="createProductModalLabel">Create New Product</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            @await Html.PartialAsync("_CreateProductForm", new Products())
        </div>
    </div>
</div>

<div class="modal fade" id="deleteProductModal" tabindex="-1" aria-labelledby="deleteProductModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            @await Html.PartialAsync("_DeleteProduct", new Products())
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var deleteProductModal = document.getElementById('deleteProductModal');
        deleteProductModal.addEventListener('show.bs.modal', function (event) {
            var button = event.relatedTarget; // Button that triggered the modal
            var productId = button.getAttribute('data-product-id'); // Extract info from data-* attributes

            var form = deleteProductModal.querySelector('form');
            var input = form.querySelector('input[name="ProductId"]');
            input.value = productId;
        });
    });
</script>

<!-- Bootstrap CSS -->
<link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet">

<!-- Bootstrap JS and dependencies (Popper.js) -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.10.2/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.min.js"></script>

Pizzario.Web/Views/Shared/_CreateCouponForm.cshtml
@model Coupons;

<form asp-action="CreateCoupon" asp-controller="Coupon" method="post" id="couponForm" novalidate>
    <div class="modal-body">
        <div>
            <label class="form-label mt-4">Coupon Code</label>
            <div class="form-floating">
                <input asp-for="CouponCode" class="form-control" id="floatingCode" required>
                <label asp-for="CouponCode">Enter coupon code here.</label>
                <div class="invalid-feedback">Please enter a coupon code.</div>
            </div>

            <label class="form-label mt-4">Discount Amount</label>
            <div class="form-floating">
                <input asp-for="DiscountAmount" class="form-control" id="floatingDisAmount" autocomplete="off" required>
                <label asp-for="DiscountAmount">Enter discount amount here.</label>
                <div class="invalid-feedback">Please enter a discount amount.</div>
            </div>

            <label class="form-label mt-4">Minimum Amount</label>
            <div class="form-floating">
                <input asp-for="MinAmount" class="form-control" id="floatingMinAmount" autocomplete="off" required>
                <label asp-for="MinAmount">Enter minimum amount here.</label>
                <div class="invalid-feedback">Please enter a minimum amount.</div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary"><i class="bi bi-save2-fill me-2"></i>Save changes</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="bi bi-x-square-fill me-2"></i>Cancel</button>
    </div>
</form>


<script>
    document.addEventListener('DOMContentLoaded', function () {
        var form = document.getElementById('couponForm');
        var modal = new bootstrap.Modal(document.getElementById('createCouponModal'));

        modal._element.addEventListener('hide.bs.modal', function () {
            form.classList.remove('was-validated');
            form.reset();
        });

        form.addEventListener('submit', function (event) {
            if (form.checkValidity() === false) {
                event.preventDefault();
                event.stopPropagation();
            }
            form.classList.add('was-validated');
        }, false);
    });
</script>

Pizzario.Web/Views/Shared/_CreateProductForm.cshtml
@model Products;

<form asp-action="CreateProduct" asp-controller="Product" method="post" id="productForm" novalidate>
    <div class="modal-body">
        <div>
            <label class="form-label mt-4">Product Name</label>
            <div class="form-floating">
                <input asp-for="ProductName" class="form-control" id="productName" required>
                <label asp-for="ProductName">Enter product name here.</label>
                <div class="invalid-feedback">Please enter a product name.</div>
            </div>

            <label class="form-label mt-4">Price</label>
            <div class="form-floating">
                <input asp-for="Price" class="form-control" id="price" autocomplete="off" required>
                <label asp-for="Price">Enter Price here.</label>
                <div class="invalid-feedback">Please enter a price.</div>
            </div>

            <label class="form-label mt-4">Description</label>
            <div class="form-floating">
                <input asp-for="Description" class="form-control" id="description" required>
                <label asp-for="Description">Enter description here.</label>
                <div class="invalid-feedback">Please enter a description.</div>
            </div>

            <label class="form-label mt-4">CategoryName</label>
            <div class="form-floating">
                <input asp-for="CategoryName" class="form-control" id="categoryName" required>
                <label asp-for="CategoryName">Enter category name here.</label>
                <div class="invalid-feedback">Please enter a category name.</div>
            </div>

           
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary"><i class="bi bi-save2-fill me-2"></i>Save changes</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="bi bi-x-square-fill me-2"></i>Cancel</button>
    </div>
</form>


<script>
    document.addEventListener('DOMContentLoaded', function () {
        var form = document.getElementById('productForm');
        var modal = new bootstrap.Modal(document.getElementById('createProductModal'));

        modal._element.addEventListener('hide.bs.modal', function () {
            form.classList.remove('was-validated');
            form.reset();
        });

        form.addEventListener('submit', function (event) {
            if (form.checkValidity() === false) {
                event.preventDefault();
                event.stopPropagation();
            }
            form.classList.add('was-validated');
        }, false);
    });
</script>

Pizzario.Web/Views/Shared/_DeleteCoupon.cshtml
@* @model Coupons;

<form asp-action="DeleteCoupon" asp-controller="Coupon">
    <input asp-for="CouponId" hidden/>
    <div class="modal-body">
        <div>
            Are you sure you want to delete this coupon?
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-danger btn-sm"><i class="bi bi-trash-fill me-2"></i>Delete</button>
        <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal"><i class="bi bi-x-square-fill me-2"></i>Cancel</button>
    </div>
</form> *@

@model Coupons;

@using (Html.BeginForm("DeleteCoupon", "Coupon", FormMethod.Post, new { @class = "my_form" }))
{
    <input asp-for="CouponId" hidden />
    <div class="modal-body">
        <div>
            Are you sure you want to delete this coupon?
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-danger btn-sm"><i class="bi bi-trash-fill me-2"></i>Delete</button>
        <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal"><i class="bi bi-x-square-fill me-2"></i>Cancel</button>
    </div>
}

Pizzario.Web/Views/Shared/_DeleteProduct.cshtml
@model Products;

@using (Html.BeginForm("DeleteProduct", "Product", FormMethod.Post, new { @class = "my_form" }))
{
    <input asp-for="ProductId" hidden />
    <div class="modal-body">
        <div>
            Are you sure you want to delete this product?
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-danger btn-sm"><i class="bi bi-trash-fill me-2"></i>Delete</button>
        <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal"><i class="bi bi-x-square-fill me-2"></i>Cancel</button>
    </div>
}

Pizzario.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pizzario.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css" />
    <link rel="stylesheet" href="~/Pizzario.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <ul class="nav nav-pills">
            <li class="nav-item">
                <a class="nav-link active" asp-controller="Home" asp-action="Index">Pizzario.Web</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Content Management</a>
                <div class="dropdown-menu" style="">
                    <a class="dropdown-item" asp-controller="Coupon" asp-action="CouponIndex">Coupon</a>
                    <a class="dropdown-item" asp-controller="Product" asp-action="ProductList">Product</a>
                </div>
            </li>
        </ul>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_Notifications" />
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="text-center">
            &copy; 2024 - Pizzario.Web - <i class="bi bi-app-indicator"></i>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Pizzario.Web/Views/Shared/_Notifications.cshtml
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}